
package cn.com.webxml;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>IP地址搜索 WEB 服务</strong>包含中国和国外已知的IP地址数据，是目前最完整的IP地址数据，记录数量现已超过37万条并还在不断更新和增加中，因IP地址在不断变化，此IP地址数据查询仅供参考。</br>此IP地址搜索Web Services请不要用于任何商业目的，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IpAddressSearchWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl")
public class IpAddressSearchWebService
    extends Service
{

    private final static URL IPADDRESSSEARCHWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.com.webxml.IpAddressSearchWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.com.webxml.IpAddressSearchWebService.class.getResource(".");
            url = new URL(baseUrl, "http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IPADDRESSSEARCHWEBSERVICE_WSDL_LOCATION = url;
    }

    public IpAddressSearchWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IpAddressSearchWebService() {
        super(IPADDRESSSEARCHWEBSERVICE_WSDL_LOCATION, new QName("http://WebXml.com.cn/", "IpAddressSearchWebService"));
    }

    /**
     * 
     * @return
     *     returns IpAddressSearchWebServiceSoap
     */
    @WebEndpoint(name = "IpAddressSearchWebServiceSoap")
    public IpAddressSearchWebServiceSoap getIpAddressSearchWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "IpAddressSearchWebServiceSoap"), IpAddressSearchWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IpAddressSearchWebServiceSoap
     */
    @WebEndpoint(name = "IpAddressSearchWebServiceSoap")
    public IpAddressSearchWebServiceSoap getIpAddressSearchWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "IpAddressSearchWebServiceSoap"), IpAddressSearchWebServiceSoap.class, features);
    }

}
