
package com.bingbing.bingxue.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>IP��ַ���� WEB ����</strong>�����й��͹�����֪��IP��ַ���ݣ���Ŀǰ��������IP��ַ���ݣ���¼�������ѳ���37���������ڲ��ϸ��º������У���IP��ַ�ڲ��ϱ仯����IP��ַ���ݲ�ѯ�����ο���</br>��IP��ַ����Web Services�벻Ҫ�����κ���ҵĿ�ģ�������Ҫ��<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">��ϵ����</a>����ӭ���������� QQ��8409035<br /><strong>ʹ�ñ�վ WEB ������ע�������ӱ�վ��http://www.webxml.com.cn/ ��л��ҵ�֧��</strong>��<br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IpAddressSearchWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl")
public class IpAddressSearchWebService
    extends Service
{

    private final static URL IPADDRESSSEARCHWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(IpAddressSearchWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = IpAddressSearchWebService.class.getResource(".");
            url = new URL(baseUrl, "http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IPADDRESSSEARCHWEBSERVICE_WSDL_LOCATION = url;
    }

    public IpAddressSearchWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IpAddressSearchWebService() {
        super(IPADDRESSSEARCHWEBSERVICE_WSDL_LOCATION, new QName("http://WebXml.com.cn/", "IpAddressSearchWebService"));
    }

    /**
     * 
     * @return
     *     returns IpAddressSearchWebServiceSoap
     */
    @WebEndpoint(name = "IpAddressSearchWebServiceSoap")
    public IpAddressSearchWebServiceSoap getIpAddressSearchWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "IpAddressSearchWebServiceSoap"), IpAddressSearchWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IpAddressSearchWebServiceSoap
     */
    @WebEndpoint(name = "IpAddressSearchWebServiceSoap")
    public IpAddressSearchWebServiceSoap getIpAddressSearchWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "IpAddressSearchWebServiceSoap"), IpAddressSearchWebServiceSoap.class, features);
    }

}
