
package com.bingbing.bingxue.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>����Ԥ�� Web ��������ÿ2.5Сʱ�����Զ�����һ�Σ�׼ȷ�ɿ������� 340 ����й���Ҫ���к� 60 ���������Ҫ���������ڵ�����Ԥ�����ݡ�</br>������Ԥ��Web Services�벻Ҫ�����κ���ҵĿ�ģ�������Ҫ��<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">��ϵ����</a>����ӭ���������� QQ��8409035<br />ʹ�ñ�վ WEB ������ע�������ӱ�վ��http://www.webxml.com.cn/ ��л��ҵ�֧��</strong>��<br /><span style="color:#999999;">֪ͨ������Ԥ�� WEB ������ԭ��ʹ�õ�ַ http://www.onhap.com/WebServices/WeatherWebService.asmx �ģ���ĳ�����ʹ�õķ����ַ http://www.webxml.com.cn/WebServices/WeatherWebService.asmx ���������ü��ɡ�</span><br /><br />&nbsp;
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WeatherWebService", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "file:/C:/Users/Administrator/Desktop/WeatherWebService.wsdl")
public class WeatherWebService
    extends Service
{

    private final static URL WEATHERWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WeatherWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = WeatherWebService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/Administrator/Desktop/WeatherWebService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Administrator/Desktop/WeatherWebService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEATHERWEBSERVICE_WSDL_LOCATION = url;
    }

    public WeatherWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherWebService() {
        super(WEATHERWEBSERVICE_WSDL_LOCATION, new QName("http://WebXml.com.cn/", "WeatherWebService"));
    }

    /**
     * 
     * @return
     *     returns WeatherWebServiceSoap
     */
    @WebEndpoint(name = "WeatherWebServiceSoap")
    public WeatherWebServiceSoap getWeatherWebServiceSoap() {
        return super.getPort(new QName("http://WebXml.com.cn/", "WeatherWebServiceSoap"), WeatherWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherWebServiceSoap
     */
    @WebEndpoint(name = "WeatherWebServiceSoap")
    public WeatherWebServiceSoap getWeatherWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "WeatherWebServiceSoap"), WeatherWebServiceSoap.class, features);
    }

}
